/*
 * OnfonMediaSMSGatewayLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ke.co.onfonmedia.api;


public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "https://api.onfonmedia.co.ke/v1/sms";

    //Network Layer Access Key
    //TODO: Replace the accessKey with an appropriate value
    public static String accessKey = "ACCESS_KEY";

    //Used for authentication purpose and pass this parameter in URL encoded format.
    //TODO: Replace the apiKey with an appropriate value
    public static String apiKey = "API_KEY";

    //Used for authentication purpose and pass this parameter in URL encoded format.
    //TODO: Replace the clientId with an appropriate value
    public static String clientId = "CLIENT_ID";

}
