/*
 * OnfonMediaSMSGatewayLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ke.co.onfonmedia.api;

import ke.co.onfonmedia.api.controllers.*;
import ke.co.onfonmedia.api.http.client.HttpClient;

public class OnfonMediaSMSGatewayClient {
    /**
     * Singleton access to Account controller
     * @return	Returns the AccountController instance 
     */
    public AccountController getAccount() {
        return AccountController.getInstance();
    }

    /**
     * Singleton access to Template controller
     * @return	Returns the TemplateController instance 
     */
    public TemplateController getTemplate() {
        return TemplateController.getInstance();
    }

    /**
     * Singleton access to SMS controller
     * @return	Returns the SMSController instance 
     */
    public SMSController getSMS() {
        return SMSController.getInstance();
    }

    /**
     * Singleton access to GROUP controller
     * @return	Returns the GROUPController instance 
     */
    public GROUPController getGROUP() {
        return GROUPController.getInstance();
    }

    /**
     * Singleton access to Campaign controller
     * @return	Returns the CampaignController instance 
     */
    public CampaignController getCampaign() {
        return CampaignController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public OnfonMediaSMSGatewayClient() {
        Configuration.accessKey = "ACCESS_KEY";
        Configuration.apiKey = "API_KEY";
        Configuration.clientId = "CLIENT_ID";
    }

    /**
     * Client initialization constructor 
     */     
    public OnfonMediaSMSGatewayClient(String accessKey, String apiKey, String clientId) {
        this();
        if(accessKey != null) Configuration.accessKey = accessKey;
        if(apiKey != null) Configuration.apiKey = apiKey;
        if(clientId != null) Configuration.clientId = clientId;
    }
}